# 测试地址
# 一般来说，代理地址是哪个，就用哪个测试
url: "https://cf.xiu2.xyz/url"

# 反向代理的端口
# 一般来说都是 443
port: 443

# 连通性测试配置
conn:
  # 连通性测试时，使用的测试方式
  # http, tcp
  method: "http"
  # 尝试建立连接的超时时间（秒）
  # 超过这个时间之后还没成功建立连接，视为连接失败
  # 即反代 IP 是无效的 IP
  timeout: 10
  # 测试完毕后，显示连接速度最快的排名靠前的数据
  # 显示数据的数量与此数字相同
  top: 10

  http:
    # http 测试中，获取响应结果的超时时间（秒）
    # 超过这个时间还没获取到响应结果，视为不可用连接
    resp_timeout: 10

download:
  # 下载速度测试中的超时时间（秒）
  # 下载测试时，单个IP的下载测试时间不会超过这个值
  timeout: 10
